#theme: jekyll-theme-hacker
permalink: /404.html

# Site settings
title: Yuzec Blog
SEOTitle: Home | Yuzec Blog
header-img: img/home-bg.jpg
email: yuzec@163.com
description: "个人博客"
keyword: "yuzec"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: yuzec
#weibo_username:     huxpro
#zhihu_username:     huxpro
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
anchorjs: true

# Gems
plugins: [jekyll-paginate]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# Sidebar settings
sidebar: true
sidebar-about-description: "Just do it!"
sidebar-avatar: img/avatar-yuzec.webp

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
